#!/bin/bash
set -e

# Set default values for configurations
: ${OWNCLOUD_DOMAIN_NAME:=cloud.example.com} # IDEA: Get default from hostname env var somehow?
: ${OWNCLOUD_SSL_CERT:=/etc/ssl/nginx/cloud.example.com.crt} # IDEA: Make this a shared volume in Dockerfile, so it can be stored.
: ${OWNCLOUD_SSL_CERT_KEY:=/etc/ssl/nginx/cloud.example.com.key}
: ${OWNCLOUD_DB_TYPE:=sqlite}
: ${OWNCLOUD_DB_NAME:=owncloud}
: ${OWNCLOUD_DB_USER:=root}
: ${OWNCLOUD_DB_PASSWORD:=}
: ${OWNCLOUD_DB_PASSWORD_SALT:=}
: ${OWNCLOUD_FORCE_SSL:=}
: ${OWNCLOUD_LOG_LEVEL:=}

# Common config edit function
set_config() {
    key="$1"
    value="$2"
    # Do a loop so sed can scale with number of files/options
    for i in $(find $CONF_DIR -type f); do
        sed -ri "s|\S*($key\s+).*|\1 $value|g" $i
    done
}

# Apply default or user specified options to config files
set_config 'server_name' "$OWNCLOUD_DOMAIN_NAME" # Should default to hostname env var of container
set_config 'ssl_certificate' "$OWNCLOUD_SSL_CERT"
set_config 'ssl_certificate_key' "$OWNCLOUD_SSL_CERT_KEY"
set_config 'dbtype' "$OWNCLOUD_DB_TYPE"
set_config 'dbname' "$OWNCLOUD_DB_NAME"
set_config 'dbuser' "$OWNCLOUD_DB_USER"
set_config 'dbpassword' "$OWNCLOUD_DB_PASSWORD" # This should work exactally like wordpress
set_config 'passwordsalt' "$OC_DB_PASSWORD_SALT" # Just like wordpress this could be set but randomly generated by default
set_config 'forcessl' "$OC_FORCE_SSL"
set_config 'loglevel' "$OC_LOG_LEVEL"


# FIX: Removed memcached as an option, since it should just be set to local anyways.
# So to implement this the default setting just has to be in config.php (maybe check for link, if needed)

# FIX: Just like wordpess check "$PHP_FPM_LISTEN" for optional unix socket setting.
# In any case setting should be taken from there and fall back to default. No user entry required.

# IDEA: If no ssl cert/key is supplied autogenerate one.
# Then if domain name is supplied rename them accordingly.

# IDEA: Check for php5-fpm env vars and duplicate the settings here.
# Then we could maybe in the future have an option for running php5-fpm in this container.

#opt_install # IDEA: Optional installation and config of php5 cache. Check wordpress entrypoint again.

exec "$@"
